# Generated by Django 4.1.2 on 2022-10-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='myapp_2.author')),
            ],
        ),
        migrations.CreateModel(
            name='Book_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.CharField(default='', max_length=200)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('issued', models.DateField(blank=True, null=True)),
                ('surrendered', models.DateField(blank=True, null=True)),
                ('book_cards', models.ManyToManyField(to='myapp_2.book')),
            ],
        ),
        migrations.CreateModel(
            name='User_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_names', to='myapp_2.book_card')),
            ],
        ),
    ]
